### PR TITLE
Make it possible to configure the tasks in the rakefile

### PR DESCRIPTION
**Pull request by ZeroPointEnergy**
This is intended as a discussion more than an actually finished PR.

When I tried to use this gem in our Rakefile I immediately had the problem that our directories are not the defaults, but it would be convenient if the rake tasks where configured in the Rakefile so they are by default doing the right thing.

The idea is to configure the locations of the Puppetfile, modules path etc. similar to how you would configure settings of your rspec rake tasks.

The provided PR makes it possible to configure the tasks in the Rakefile with:
```
Ra10ke::RakeTask.new do |t|
  t.basedir = File.join(Dir.pwd, 'my_custom/modules/path')
  t.force = true                                  
end
```

What do you think?

### CODE REVIEW

**Comment by bastelfreak** [comment]
To me this looks good and useful. Can you please update the README.md?

**Comment by ZeroPointEnergy** [comment]
Had to change how the solve_dependencies task is added so it can use the settings as well.
we could probably separate the other tasks in the same manner, would make the main class a bit cleaner.

**Comment by bastelfreak** [comment]
I'm fine with this as it currently is. Is this still WIP from your point of view?

**Comment by ZeroPointEnergy** [comment]
I removed the WIP, I think this is ready.

**Pull request merged**
