### PR TITLE
New release

### PR DESCRIPTION
**Pull request by ZeroPointEnergy**
Not sure if this is the right process for a rubygem release. Let me know if I have to do something different to help with a new release.

### CODE REVIEW

**Comment by bastelfreak** [comment]
Should we wait with the release until the other open PR is merged?

**Comment by ZeroPointEnergy** [comment]
Yeah I think we should wait. I will update the change log once it is merged.

**Comment by logicminds** [comment]
@ZeroPointEnergy #35 has been merged

**Comment by logicminds** [comment]
Closing due to duplicate PR.

**Pull request closed without merging**
