### PR TITLE
Release 2.0.0

### PR DESCRIPTION
**Pull request by bastelfreak**
@logicminds do you plan more breaking changes in the near future or can we do a 2.0.0 release already?

### CODE REVIEW

**Comment by logicminds** [comment]
I had some more changes I wanted to merge in.  But they are more features rather than breaking changes.  Still hoping to get them on the 2.0 train.

**Comment by bastelfreak** [comment]
we can probably wait a few days with the next release. But doing more minor releases is fairly trivial and we can always do them within a few minutes if required.

**Comment by logicminds** [comment]
Please rebase and regenerate the changelog.

**Comment by bastelfreak** [comment]
updated it

**Review by root-expert — APPROVED** [review]

**Pull request merged**
